### ISSUE TITLE
你好，请问高并发情况下，如何控制内存增长？

### ISSUE THREAD

**Issue by SliverBullet5563** [cxapython/unidbg-server#1]

**Comment by cxapython** [comment]
你好 我这个只是服务的demo&nbsp; 高并发的问题还没试 你可以研究下



---原始邮件---
发件人: "SilverBullet"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 下午5:43
收件人: "cxapython/unidbg-server"<unidbg-server@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [cxapython/unidbg-server] 你好，请问高并发情况下，如何控制内存增长？ (#1)

**Comment by SuperYogurt** [comment]
问题解决了吗？老兄

**Comment by SliverBullet5563** [comment]
目前解决了，用线程池开启固定实例复用线程，可以不用销毁，看作者 com.bytedance.frameworks.core.encrypt.TTEncryptWorker这个类
linux服务器下用这个，应该是使用dynarmic模拟器：
static {
    DynarmicLoader.forceUseDynarmic();
}
我的代码借你参考下，你试试，目前高并发的服务是可以的
public class SignController {

    static {
        DynarmicLoader.forceUseDynarmic();
    }

    final int processors = Runtime.getRuntime().availableProcessors()/2 +2;
    final WorkerPool xgPool = WorkerPoolFactory.create(new WorkerFactory() {
        @Override
        public Worker createWorker() {
            return new XGWorker();
        }
    }, processors);

    final static ExecutorService executorXG = Executors.newFixedThreadPool(50);

    @RequestMapping(value="getXG",method =  {RequestMethod.POST},produces = "application/json;charset=UTF-8")
    @ResponseBody
    public String dySign(@RequestBody JSONObject params) {
        try{
            System.out.println("param: "+params.toString());
            String cookie = params.getString("cookie");
            String url = params.getString("url");
            String stub = params.getString("X-SS-STUB");

            System.out.println("cookie: "+cookie);
            System.out.println("url: "+url);
            System.out.println("stub: "+stub);

            Future<Map<String, String&gt;&gt; submit = executorXG.submit(new Callable<Map<String, String&gt;&gt;() {
                @Override
                public Map<String, String&gt; call() {
                    XGWorker worker = xgPool.borrow(1, TimeUnit.MINUTES);
                    if (worker != null) {
                        try {
                            return worker.worker(url,cookie,stub);
                        }catch (Throwable throwable){
                            System.err.println("XGWorker error: "+throwable);
                        }
                        finally {
                            xgPool.release(worker);
                        }
                    } else {
                        System.err.println("XGWorker Borrow failed");
                    }

                    return null;
                }
            });
            Map<String,String&gt; result= submit.get();
            return JSON.toJSONString(result);

        }catch (Throwable throwable){
            throwable.printStackTrace();
            System.out.println("dySign throwable: "+throwable.toString());
            return null;
        }

    }
}


public class XGWorker implements Worker,IWorker<Map<String,String&gt;&gt; {
    private final DouyinSign douyinSign;

    public XGWorker(){
        douyinSign = new DouyinSign();
        System.out.println("Create: " + douyinSign);
    }
    @Override
    public void close() throws IOException {
        System.out.println("XGWorker close()");
        douyinSign.destroy();
    }


    @Override
    public Map<String, String&gt; worker(String... args) {
        System.out.println("XGWorker worker: "+Thread.currentThread().getName()+Thread.currentThread().getId());
        String url = args[0];
        String cookie = args[1];
        String stub = args[2];
        return douyinSign.crack(url,cookie,stub);
    }
}


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cxapython/unidbg-server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 上午10:25
收件人:&nbsp;"cxapython/unidbg-server"<unidbg-server@noreply.github.com&gt;;
抄送:&nbsp;"silverbullet5563（资料打印）"<2441928193@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cxapython/unidbg-server] 你好，请问高并发情况下，如何控制内存增长？ (#1)





 
问题解决了吗？老兄

**Comment by SuperYogurt** [comment]
好的，谢谢，老哥



---原始邮件---
发件人: "SilverBullet"<notifications@github.com&gt;
发送时间: 2021年1月27日(周三) 中午1:58
收件人: "cxapython/unidbg-server"<unidbg-server@noreply.github.com&gt;;
抄送: "SuperYogurt"<2692666356@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [cxapython/unidbg-server] 你好，请问高并发情况下，如何控制内存增长？ (#1)




 目前解决了，用线程池开启固定实例复用线程，可以不用销毁，看作者 com.bytedance.frameworks.core.encrypt.TTEncryptWorker这个类 
 linux服务器下用这个，应该是使用dynarmic模拟器： 
 static { 
     DynarmicLoader.forceUseDynarmic(); 
 } 
 我的代码借你参考下，你试试，目前高并发的服务是可以的 
 public class SignController { 
 
     static { 
         DynarmicLoader.forceUseDynarmic(); 
     } 
 
     final int processors = Runtime.getRuntime().availableProcessors()/2 +2; 
     final WorkerPool xgPool = WorkerPoolFactory.create(new WorkerFactory() { 
         @Override 
         public Worker createWorker() { 
             return new XGWorker(); 
         } 
     }, processors); 
 
     final static ExecutorService executorXG = Executors.newFixedThreadPool(50); 
 
     @RequestMapping(value="getXG",method =  {RequestMethod.POST},produces = "application/json;charset=UTF-8") 
     @ResponseBody 
     public String dySign(@RequestBody JSONObject params) { 
         try{ 
             System.out.println("param: "+params.toString()); 
             String cookie = params.getString("cookie"); 
             String url = params.getString("url"); 
             String stub = params.getString("X-SS-STUB"); 
 
             System.out.println("cookie: "+cookie); 
             System.out.println("url: "+url); 
             System.out.println("stub: "+stub); 
 
             Future<Map<String, String&amp;gt;&amp;gt; submit = executorXG.submit(new Callable<Map<String, String&amp;gt;&amp;gt;() { 
                 @Override 
                 public Map<String, String&amp;gt; call() { 
                     XGWorker worker = xgPool.borrow(1, TimeUnit.MINUTES); 
                     if (worker != null) { 
                         try { 
                             return worker.worker(url,cookie,stub); 
                         }catch (Throwable throwable){ 
                             System.err.println("XGWorker error: "+throwable); 
                         } 
                         finally { 
                             xgPool.release(worker); 
                         } 
                     } else { 
                         System.err.println("XGWorker Borrow failed"); 
                     } 
 
                     return null; 
                 } 
             }); 
             Map<String,String&amp;gt; result= submit.get(); 
             return JSON.toJSONString(result); 
 
         }catch (Throwable throwable){ 
             throwable.printStackTrace(); 
             System.out.println("dySign throwable: "+throwable.toString()); 
             return null; 
         } 
 
     } 
 } 
 
 
 public class XGWorker implements Worker,IWorker<Map<String,String&amp;gt;&amp;gt; { 
     private final DouyinSign douyinSign; 
 
     public XGWorker(){ 
         douyinSign = new DouyinSign(); 
         System.out.println("Create: " + douyinSign); 
     } 
     @Override 
     public void close() throws IOException { 
         System.out.println("XGWorker close()"); 
         douyinSign.destroy(); 
     } 
 
 
     @Override 
     public Map<String, String&amp;gt; worker(String... args) { 
         System.out.println("XGWorker worker: "+Thread.currentThread().getName()+Thread.currentThread().getId()); 
         String url = args[0]; 
         String cookie = args[1]; 
         String stub = args[2]; 
         return douyinSign.crack(url,cookie,stub); 
     } 
 } 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "cxapython/unidbg-server"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2021年1月27日(星期三) 上午10:25 
 收件人:&amp;nbsp;"cxapython/unidbg-server"<unidbg-server@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"silverbullet5563（资料打印）"<2441928193@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [cxapython/unidbg-server] 你好，请问高并发情况下，如何控制内存增长？ (#1) 
 
 
 
 
 
   
 问题解决了吗？老兄

**Comment by cxapython** [comment]
> 目前解决了，用线程池开启固定实例复用线程，可以不用销毁，看作者 com.bytedance.frameworks.core.encrypt.TTEncryptWorker这个类 linux服务器下用这个，应该是使用dynarmic模拟器： static { DynarmicLoader.forceUseDynarmic(); } 我的代码借你参考下，你试试，目前高并发的服务是可以的 public class SignController { static { DynarmicLoader.forceUseDynarmic(); } final int processors = Runtime.getRuntime().availableProcessors()/2 +2; final WorkerPool xgPool = WorkerPoolFactory.create(new WorkerFactory() { @override public Worker createWorker() { return new XGWorker(); } }, processors); final static ExecutorService executorXG = Executors.newFixedThreadPool(50); @RequestMapping(value="getXG",method = {RequestMethod.POST},produces = "application/json;charset=UTF-8") @responsebody public String dySign(@requestbody JSONObject params) { try{ System.out.println("param: "+params.toString()); String cookie = params.getString("cookie"); String url = params.getString("url"); String stub = params.getString("X-SS-STUB"); System.out.println("cookie: "+cookie); System.out.println("url: "+url); System.out.println("stub: "+stub); Future<Map<String, String&gt;&gt; submit = executorXG.submit(new Callable<Map<String, String&gt;&gt;() { @override public Map<String, String&gt; call() { XGWorker worker = xgPool.borrow(1, TimeUnit.MINUTES); if (worker != null) { try { return worker.worker(url,cookie,stub); }catch (Throwable throwable){ System.err.println("XGWorker error: "+throwable); } finally { xgPool.release(worker); } } else { System.err.println("XGWorker Borrow failed"); } return null; } }); Map<String,String&gt; result= submit.get(); return JSON.toJSONString(result); }catch (Throwable throwable){ throwable.printStackTrace(); System.out.println("dySign throwable: "+throwable.toString()); return null; } } } public class XGWorker implements Worker,IWorker<Map<String,String&gt;&gt; { private final DouyinSign douyinSign; public XGWorker(){ douyinSign = new DouyinSign(); System.out.println("Create: " + douyinSign); } @override public void close() throws IOException { System.out.println("XGWorker close()"); douyinSign.destroy(); } @override public Map<String, String&gt; worker(String... args) { System.out.println("XGWorker worker: "+Thread.currentThread().getName()+Thread.currentThread().getId()); String url = args[0]; String cookie = args[1]; String stub = args[2]; return douyinSign.crack(url,cookie,stub); } }
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cxapython/unidbg-server" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月27日(星期三) 上午10:25 收件人:&nbsp;"cxapython/unidbg-server"<unidbg-server@noreply.github.com&gt;; 抄送:&nbsp;"silverbullet5563（资料打印）"<2441928193@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cxapython/unidbg-server] 你好，请问高并发情况下，如何控制内存增长？ (#1) 问题解决了吗？老兄 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢 已更新
